apiVersion: v1
kind: ServiceAccount
metadata:
  name: ns-cleaner-operator
  labels:
    application: ns-cleaner-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ns-cleaner-operator
  labels:
    application: ns-cleaner-operator
rules:
  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch, patch]
  - apiGroups: [""]
    resources: [namespaces/status]
    verbs: [patch]
  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
  # test for pods
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "list"]
  # ns-cleaner-operator
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: [list]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ns-cleaner-operator
  labels:
    application: ns-cleaner-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ns-cleaner-operator
subjects:
  - kind: ServiceAccount
    name: ns-cleaner-operator
    namespace: ns-cleaner-operator
