# permissions for end users to edit cleaners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cleaner-editor-role
rules:
- apiGroups:
  - core.cleaner.com
  resources:
  - cleaners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.cleaner.com
  resources:
  - cleaners/status
  verbs:
  - get
