# permissions for end users to view cleaners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cleaner-viewer-role
rules:
- apiGroups:
  - core.cleaner.com
  resources:
  - cleaners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.cleaner.com
  resources:
  - cleaners/status
  verbs:
  - get
- apiGroups: [apiextensions.k8s.io]
  resources: [customresourcedefinitions]
  verbs: [list, watch]
- apiGroups: [""]
  resources: [namespaces]
  verbs: [list, watch, patch]
- apiGroups: [""]
  resources: [namespaces/status]
  verbs: [patch]
# Framework: posting the events about the handlers progress/errors.
- apiGroups: [""]
  resources: [events]
  verbs: [create]
# remove-empty-ns-operator
- apiGroups: ["*"]
  resources: ["*"]
  verbs: [list]
- apiGroups: [""]
  resources: [namespaces]
  verbs: [delete]
