name: Build and push image

on:
  push:
    branches:
      - 'v2'
  release:
    types: [released]
  workflow_dispatch:


jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: ['1.18.6']

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build binary
        run: |
          make build

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: excite13/ns-cleaner
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
